### PR TITLE
DM-41994-v24: Speed up galsim interface with meas_extensions_shapeHSM

### PR DESCRIPTION
**Pull request by mwittgen**
Accumulated PR including v24 backported tickets for review:
[DM-30947](https://jira.lsstcorp.org/browse/DM-30947?src=confmacro)
[DM-41489](https://jira.lsstcorp.org/browse/DM-41489?src=confmacro)
[DM-41994](https://jira.lsstcorp.org/browse/DM-41994?src=confmacro)
[DM-41908](https://jira.lsstcorp.org/browse/DM-41908?src=confmacro)

Individual PR will be merged in this order to preserve the backport history

### CODE REVIEW

**Comment by arunkannawadi** [comment]
The order of commits don't appear to the same in which they landed. Is that okay?

**Review by arunkannawadi — APPROVED** [review]

**Comment by mwittgen** [comment]
The tickets will be merged in this order:
[DM-30947](https://jira.lsstcorp.org/browse/DM-30947?src=confmacro)
[DM-41489](https://jira.lsstcorp.org/browse/DM-41489?src=confmacro)
[DM-41994](https://jira.lsstcorp.org/browse/DM-41994?src=confmacro)
[DM-41908](https://jira.lsstcorp.org/browse/DM-41908?src=confmacro)
Merge DM-30947 to v24.0.x then rebase and merge DM-41489
In the end this will add all those commits.

**Comment by arunkannawadi** [comment]
No, the order should be this: 1) DM-30947 2) DM-41908 3) DM-41994 and finally 4) DM-41489. This is the order in which tickets landed here, and will ensure that the package can be built at any intermediate stage as well.

**Comment by mwittgen** [comment]
I will fix this

**Pull request merged**
